trigger: none

pool:
  name: kashi_agent_pool

stages:
- stage: pipelineinfra
  displayName: "Pipeline Infra"
  jobs:
  - job: build
    displayName: "Build Job"
    steps:
    - task: TerraformTask@5
      inputs:
        provider: 'azurerm'
        command: 'init'
        workingDirectory: '$(System.DefaultWorkingDirectory)/ENV/DEV'
        backendServiceArm: 'Azure subscription 1(e59b3be3-2cd8-493e-a182-a6b8da13eccc)'
        backendAzureRmStorageAccountName: 'shashistg21'
        backendAzureRmContainerName: 'cont21'
        backendAzureRmKey: 'terraform.tfstate'
